"""Market Data Service V1 constants."""

MARKET_DATA_VERSION = "1.0"

DEFAULT_STALE_THRESHOLD_SECONDS = 120
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 30
DEFAULT_MAX_BACKOFF_SECONDS = 60
DEFAULT_BACKFILL_LIMIT = 500

SUPPORTED_SYMBOLS = ("BTC", "ETH", "SOL")
