"""Reason codes and specification-frozen default parameters."""

from decimal import Decimal

STRATEGY_VERSION = "1.0.0"

# Warmup minimums (Strategy Spec §3.1)
MIN_DAILY_CANDLES = 21
MIN_WEEKLY_CANDLES = 50
MIN_MONTHLY_CANDLES = 20

# Specification Freeze defaults
DEFAULT_SYMBOLS = ("BTC", "ETH", "SOL")
DEFAULT_MONTHLY_EMA_PERIOD = 20
DEFAULT_WEEKLY_EMA_FAST = 20
DEFAULT_WEEKLY_EMA_SLOW = 50
DEFAULT_DAILY_EMA_PERIOD = 20
DEFAULT_BREAKOUT_LOOKBACK = 20
DEFAULT_ATR_PERIOD = 14
DEFAULT_VOLUME_SMA_PERIOD = 20
DEFAULT_VOLUME_RATIO_MIN = Decimal("1.00")
DEFAULT_PULLBACK_EMA_TOLERANCE = Decimal("0.005")
DEFAULT_STOP_INITIAL_ATR_MULT = Decimal("2.5")
DEFAULT_TRAIL_ATR_MULT = Decimal("3.0")
